# Generated by Django 4.2.10 on 2025-12-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部署名')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='監視グループ名')),
                ('responsible_contact', models.TextField(help_text='カンマ区切り', verbose_name='責任者連絡先')),
                ('cc_contact', models.TextField(blank=True, verbose_name='CC用連絡先')),
                ('alert_email', models.TextField(verbose_name='アラート通知先')),
                ('report_email', models.TextField(verbose_name='レポート送付先')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department', verbose_name='申請部署')),
            ],
        ),
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='アカウント名')),
                ('provider', models.CharField(choices=[('AWS', 'AWS'), ('Azure', 'Azure'), ('GCP', 'Google Cloud'), ('OCI', 'Oracle Cloud'), ('Other', 'その他')], max_length=20, verbose_name='種別')),
                ('account_id', models.CharField(max_length=100, unique=True, verbose_name='アカウントID')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='依頼日')),
                ('connection_date', models.DateField(blank=True, null=True, verbose_name='接続日')),
                ('status', models.CharField(choices=[('Waiting', '未接続'), ('Connected', '接続済み'), ('Disconnected', '解除済み')], default='Waiting', max_length=20, verbose_name='状態')),
                ('monitor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.monitorgroup', verbose_name='監視グループ')),
            ],
        ),
    ]
