# Generated by Django 4.2.10 on 2025-12-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorgroup',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='監視グループID'),
        ),
    ]
